# Generated by Django 3.1.2 on 2022-03-24 18:59

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='College',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('rating', models.DecimalField(decimal_places=1, max_digits=2)),
                ('district', models.CharField(max_length=100)),
                ('state', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Lecturer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('qualification', models.TextField(help_text='Enter the qualification of lecturer', max_length=1000)),
                ('rating', models.DecimalField(decimal_places=1, max_digits=2)),
                ('district', models.CharField(max_length=100)),
                ('state', models.CharField(max_length=100)),
                ('department', models.CharField(max_length=100)),
                ('email', models.CharField(max_length=100)),
                ('college', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='catalog.college')),
            ],
        ),
        migrations.CreateModel(
            name='LecturerFeedback',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, help_text='Unique ID for this particular book across whole library', primary_key=True, serialize=False)),
                ('one', models.IntegerField()),
                ('two', models.IntegerField()),
                ('lecturer', models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, to='catalog.lecturer')),
            ],
        ),
        migrations.CreateModel(
            name='CollegeFeedback',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, help_text='Unique ID for this particular book across whole library', primary_key=True, serialize=False)),
                ('one', models.IntegerField()),
                ('two', models.IntegerField()),
                ('college', models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, to='catalog.college')),
            ],
        ),
    ]
