# Generated by Django 3.2.9 on 2022-01-12 15:29

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('founder_name', models.CharField(max_length=100)),
                ('date_of_est', models.DateField(blank=True, null=True)),
            ],
            options={
                'ordering': ['name', 'founder_name'],
            },
        ),
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(help_text='Enter a breif description of the job', max_length=1000)),
                ('company', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='catalog.company')),
            ],
        ),
        migrations.CreateModel(
            name='JobInstance',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, help_text='Unique ID for this particular book across whole library', primary_key=True, serialize=False)),
                ('location', models.CharField(max_length=200)),
                ('last_date', models.DateField(blank=True, null=True)),
                ('status', models.CharField(blank=True, choices=[('o', 'Occupied'), ('a', 'Available'), ('r', 'Reserved')], default='o', help_text='Job availability', max_length=1)),
                ('job', models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, to='catalog.job')),
            ],
            options={
                'ordering': ['last_date'],
            },
        ),
        migrations.CreateModel(
            name='Skill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Enter a skill (e.g. Web development)', max_length=200)),
            ],
        ),
        migrations.RemoveField(
            model_name='book',
            name='author',
        ),
        migrations.RemoveField(
            model_name='book',
            name='genre',
        ),
        migrations.RemoveField(
            model_name='bookinstance',
            name='book',
        ),
        migrations.DeleteModel(
            name='Author',
        ),
        migrations.DeleteModel(
            name='Book',
        ),
        migrations.DeleteModel(
            name='BookInstance',
        ),
        migrations.DeleteModel(
            name='Genre',
        ),
        migrations.AddField(
            model_name='job',
            name='skills',
            field=models.ManyToManyField(help_text='Select skills required for the job', to='catalog.Skill'),
        ),
    ]
