# Generated by Django 3.1.2 on 2022-03-24 21:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0007_crating_lrating'),
    ]

    operations = [
        migrations.RenameField(
            model_name='crating',
            old_name='lecturer',
            new_name='college',
        ),
    ]
