# Generated by Django 3.1.2 on 2022-03-25 06:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0010_auto_20220325_0510'),
    ]

    operations = [
        migrations.AddField(
            model_name='crating',
            name='total',
            field=models.DecimalField(decimal_places=2, max_digits=3, null=True),
        ),
        migrations.AddField(
            model_name='lrating',
            name='total',
            field=models.DecimalField(decimal_places=2, max_digits=3, null=True),
        ),
    ]
