# Generated by Django 3.1.2 on 2022-03-25 08:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0013_ctotal_ltotal'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ctotal',
        ),
        migrations.DeleteModel(
            name='ltotal',
        ),
    ]
