# Generated by Django 3.1.2 on 2022-03-26 05:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0014_auto_20220325_1422'),
    ]

    operations = [
        migrations.AlterField(
            model_name='college',
            name='rating',
            field=models.DecimalField(decimal_places=2, max_digits=5),
        ),
        migrations.AlterField(
            model_name='lecturer',
            name='rating',
            field=models.DecimalField(decimal_places=2, max_digits=5),
        ),
    ]
