# Generated by Django 4.0.3 on 2022-03-26 08:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0016_alter_college_percentage_of_student_above_60_and_more'),
        ('catalog', '0016_auto_20220326_1054'),
    ]

    operations = [
    ]
