# Generated by Django 3.1.2 on 2022-03-26 09:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0017_merge_20220326_1344'),
        ('catalog', '0018_auto_20220326_1332'),
    ]

    operations = [
    ]
